# (id, 제목 정규식, 작곡가 정규식, 악기 우선순위, 소스 우선순위, 한글 제목, 부제, 작곡가 표기, 마디 수, 덮어쓰기)
C = [
 ('swan_lake', r'^Swan Lake \(ballet\)', 'Tchaik', ['Violin','Piano'], ['pdmx','pdmx2'], '백조의 호수 주제', 'Swan Lake Op.20 — 정경(백조의 주제)', '표트르 차이콥스키 (Pyotr Ilyich Tchaikovsky, 1840–1893)', 12, {}),
 ('radetzky', r'^Radetzky-Marsch', 'Strauss', ['Piano'], ['pdmx2'], '라데츠키 행진곡', 'Radetzky-Marsch Op.228 — 주제', '요한 슈트라우스 1세 (Johann Strauss I, 1804–1849)', 16, {}),
 ('salut', r"^Salut d'amour", 'Elgar', ['Piano'], ['pdmx2'], '사랑의 인사', "Salut d'amour Op.12", '에드워드 엘가 (Edward Elgar, 1857–1934)', 16, {}),
 ('cancan', r'^Can-Can - Offenbach|^Orphée aux enfers', 'Offenbach', ['Piano'], ['pdmx2'], '캉캉 (천국과 지옥)', 'Galop infernal (Can-Can) — 지옥의 오르페우스', '자크 오펜바흐 (Jacques Offenbach, 1819–1880)', 16, {}),
 ('canon', r'^Canon in D$', 'Pachelbel', ['Piano','Violin'], ['pdmx2','mutopia'], '캐논', 'Canon in D — 주제 선율', '요한 파헬벨 (Johann Pachelbel, 1653–1706)', 16, {}),
 ('jesu', r"^Jesu Joy of Man's Desiring", 'Bach', ['Piano','Guitar'], ['pdmx2'], '예수, 인류 소망의 기쁨', "Jesu, Joy of Man's Desiring BWV 147", '요한 제바스티안 바흐 (Johann Sebastian Bach, 1685–1750)', 12, {}),
 ('william_tell', r'^Guillaume Tell$|^WILLIAM TELL$', 'Rossini', ['Piano'], ['pdmx2'], '윌리엄 텔 서곡 주제', 'Guillaume Tell — 서곡 피날레(갤럽) 주제', '조아키노 로시니 (Gioachino Rossini, 1792–1868)', 16, {}),
 ('la_donna', r"^la Donna 'e Mobile", 'Verdi', ['Piano'], ['pdmx2'], '여자의 마음 (라 돈나 에 모빌레)', 'La donna è mobile — 리골레토', '주세페 베르디 (Giuseppe Verdi, 1813–1901)', 16, {}),
 ('hungarian5', r'^Hungarian Dance No\. 5', 'Brahms', ['Piano'], ['pdmx2'], '헝가리 무곡 5번 주제', 'Hungarian Dance No.5 — 주제', '요하네스 브람스 (Johannes Brahms, 1833–1897)', 16, {}),
 ('prince_denmark', r"^Prince of Denmark's March", 'Clarke', ['Trumpet'], ['pdmx'], '덴마크 왕자의 행진 (트럼펫 볼런터리)', "Prince of Denmark's March (Trumpet Voluntary)", '제러마이어 클라크 (Jeremiah Clarke, 1674–1707)', 16, {}),
 ('rondeau', r'^Rondeau from Abdelazer', 'Purcell', ['Piano'], ['pdmx2'], '론도 (압델라자르)', 'Rondeau from Abdelazer Z.570', '헨리 퍼셀 (Henry Purcell, 1659–1695)', 16, {}),
 ('boccherini', r'^Menuett - Luigi Boccherini|^Menuet du quintette', 'Boccherini', ['Clarinet','Piano'], ['pdmx','pdmx2'], '보케리니 미뉴에트', 'Minuet — 현악 5중주 Op.11 No.5', '루이지 보케리니 (Luigi Boccherini, 1743–1805)', 16, {}),
 ('k545', r'^Sonate 16 in C major, K 545|K\.? ?545', 'Mozart', ['Piano','Flute'], ['mutopia','pdmx','pdmx2'], '피아노 소나타 16번 K.545 1악장 주제', 'Piano Sonata No.16 K.545 — 1악장 주제', '볼프강 아마데우스 모차르트 (Wolfgang Amadeus Mozart, 1756–1791)', 12, {}),
 ('anh5', r'^2 Sonatinas for Piano Anh\.5', 'Beethoven', ['Piano'], ['pdmx2'], '소나티네 G장조 (베토벤)', 'Sonatina in G major Anh.5 No.1 — 1악장 주제', '루트비히 판 베토벤 (Ludwig van Beethoven, 1770–1827)', 16, {}),
 ('sleeping', r'^The Sleeping Beauty \(ballet\)', 'Tchaik', ['Clarinet','Piano'], ['pdmx','pdmx2'], '잠자는 숲속의 미녀 왈츠', 'The Sleeping Beauty Op.66 — 왈츠 주제', '표트르 차이콥스키 (Pyotr Ilyich Tchaikovsky, 1840–1893)', 16, {}),
 ('barcarolle', r'^Barcarolle$', 'Offenbach', ['Flute'], ['pdmx'], '뱃노래 (호프만의 이야기)', 'Barcarolle — 호프만의 이야기', '자크 오펜바흐 (Jacques Offenbach, 1819–1880)', 16, {}),
 ('meditation', r'^Méditation \(Thaïs\)', 'Massenet', ['Flute'], ['pdmx'], '타이스의 명상곡', 'Méditation — 타이스', '쥘 마스네 (Jules Massenet, 1842–1912)', 12, {}),
 ('swan', r'^Le carnaval des animaux', 'Saint', ['Violin','Piano'], ['pdmx','pdmx2'], '백조 (동물의 사육제)', 'Le Cygne — 동물의 사육제', '카미유 생상스 (Camille Saint-Saëns, 1835–1921)', 16, {}),
 ('sheep', r'^Schafe können sicher weiden', 'Bach', ['Cello'], ['pdmx'], '양들은 한가로이 풀을 뜯고', 'Schafe können sicher weiden BWV 208', '요한 제바스티안 바흐 (Johann Sebastian Bach, 1685–1750)', 12, {}),
 ('arioso', r'^Arioso$|^Arioso BWV 156', 'Bach', ['Violin','Piano'], ['pdmx','mutopia'], '아리오소', 'Arioso BWV 156', '요한 제바스티안 바흐 (Johann Sebastian Bach, 1685–1750)', 12, {}),
 ('minuet_woo10', r'^6 Minuets WoO 10', 'Beethoven', ['Violin'], ['pdmx'], '베토벤 미뉴에트 G장조', 'Minuet in G WoO 10 No.2', '루트비히 판 베토벤 (Ludwig van Beethoven, 1770–1827)', 16, {}),
 ('ecossaise', r'^Ecossaise WoO 86', 'Beethoven', ['Piano'], ['pdmx2'], '에코세즈', 'Écossaise WoO 86', '루트비히 판 베토벤 (Ludwig van Beethoven, 1770–1827)', 16, {}),
 ('wooden', r'^March of the Wooden Soldiers', 'Tchaik', ['Piano'], ['mutopia'], '나무 병정의 행진', 'March of the Wooden Soldiers — 어린이 앨범 Op.39 No.5', '표트르 차이콥스키 (Pyotr Ilyich Tchaikovsky, 1840–1893)', 16, {}),
 ('old_french', r'^Old French Song, Op\. 39', 'Tchaik', ['Piano'], ['mutopia'], '옛 프랑스 노래', 'Old French Song — 어린이 앨범 Op.39 No.16', '표트르 차이콥스키 (Pyotr Ilyich Tchaikovsky, 1840–1893)', 16, {}),
 ('brahms_waltz', r'^Waltz Op39 15', 'Brahms', ['Piano'], ['mutopia'], '브람스 왈츠 Op.39-15', 'Waltz Op.39 No.15', '요하네스 브람스 (Johannes Brahms, 1833–1897)', 16, {}),
 ('susanna', r'^oh susanna', 'Foster', ['Piano'], ['pdmx2'], '오 수재너', 'Oh! Susanna', '스티븐 포스터 (Stephen Foster, 1826–1864)', 16, {}),
 ('camptown', r'^Camptown Races', 'Foster', ['Piano'], ['pdmx2'], '캠프타운 경마', 'Camptown Races', '스티븐 포스터 (Stephen Foster, 1826–1864)', 16, {}),
 ('old_folks', r'^Old Folks at Home|^OLD FOLKS AT HOME', 'Foster', ['Piano'], ['pdmx2'], '스와니 강 (고향 사람들)', 'Old Folks at Home (Swanee River)', '스티븐 포스터 (Stephen Foster, 1826–1864)', 16, {}),
 ('home_sweet', r'^Home, Sweet Home', 'Bishop', ['Voice','Voice+Piano'], ['mutopia','openscore_lieder'], '즐거운 나의 집', 'Home, Sweet Home', '헨리 비숍 (Henry Bishop, 1786–1855)', 16, {}),
 ('eine_kleine', r'^Eine kleine Nachtmusik K\.525', 'Mozart', ['Flute'], ['pdmx'], '아이네 클라이네 나흐트무지크', 'Eine kleine Nachtmusik K.525 — 1악장 주제', '볼프강 아마데우스 모차르트 (Wolfgang Amadeus Mozart, 1756–1791)', 12, {}),
 ('minuet_f', r'^Minuet in F major BWV Anh\.113', 'Bach', ['Piano'], ['pdmx2'], '미뉴에트 F장조', 'Minuet in F major BWV Anh.113 (안나 막달레나 바흐 소곡집)', '작자 미상 · 바흐 소곡집 수록', 16, {}),
 ('march_d', r'^March in D Major$', 'Bach', ['Violin'], ['pdmx'], '행진곡 D장조', 'March in D major BWV Anh.122 (안나 막달레나 바흐 소곡집)', '카를 필리프 에마누엘 바흐 (C. P. E. Bach, 1714–1788)', 16, {}),
 ('polonaise_g', r'^Polonaise in G minor, BWV Anh\. 119', 'Bach', ['Piano'], ['mutopia'], '폴로네즈 G단조', 'Polonaise in G minor BWV Anh.119 (안나 막달레나 바흐 소곡집)', '작자 미상 · 바흐 소곡집 수록', 16, {}),
 ('solveig', r'^solveigs song', 'Grieg', ['Cello'], ['pdmx'], '솔베이지의 노래', "Solveig's Song — 페르귄트 Op.55", '에드바르 그리그 (Edvard Grieg, 1843–1907)', 16, {}),
 ('mountain_king', r'^In the Hall of the Mountain King', 'Grieg', ['Piano'], ['mutopia'], '산왕의 궁전에서', 'In the Hall of the Mountain King — 페르귄트 Op.46', '에드바르 그리그 (Edvard Grieg, 1843–1907)', 16, {}),
 ('anitra', r"^Anitra's Dance", 'Grieg', ['Violin'], ['mutopia'], '아니트라의 춤', "Anitra's Dance — 페르귄트 Op.46", '에드바르 그리그 (Edvard Grieg, 1843–1907)', 16, {}),
 ('beethoven5', r'^Beethoven Fifth Op67', 'Beethoven', ['Piano'], ['mutopia'], '운명 교향곡 주제', 'Symphony No.5 Op.67 — 1악장 주제', '루트비히 판 베토벤 (Ludwig van Beethoven, 1770–1827)', 12, {}),
 ('danse_macabre', r'^Danse macabre', 'Saint', ['Violin'], ['pdmx'], '죽음의 무도 주제', 'Danse macabre Op.40 — 주제', '카미유 생상스 (Camille Saint-Saëns, 1835–1921)', 16, {}),
 ('martini', r'^Gavotte$', 'Martini', ['Piano'], ['mutopia'], '마르티니 가보트', 'Gavotte', '조반니 바티스타 마르티니 (Giovanni Battista Martini, 1706–1784)', 16, {}),
 ('sww19_6', r'^Lieder ohne Worte, Op\.19 No\.6', 'Mendelssohn', ['Piano'], ['mutopia'], '베네치아의 뱃노래', 'Venetianisches Gondellied — 무언가 Op.19 No.6', '펠릭스 멘델스존 (Felix Mendelssohn, 1809–1847)', 16, {}),
 ('emperor', r'^Streichquartett Op\. 76 No\. 3', 'Haydn', ['Piano'], ['pdmx2'], '황제 4중주 주제 (하이든)', 'Emperor Quartet Op.76 No.3 — 2악장 주제', '요제프 하이든 (Joseph Haydn, 1732–1809)', 16, {}),
 ('k331_theme', r'^Sonate Opus KV 331 - Tema', 'Mozart', ['Piano'], ['mutopia'], '피아노 소나타 K.331 1악장 주제', 'Sonata K.331 — Andante grazioso 주제', '볼프강 아마데우스 모차르트 (Wolfgang Amadeus Mozart, 1756–1791)', 16, {}),
 ('clementi36', r'^Sonatina No1\.2 Muzio Clementi', 'Clementi', ['Piano'], ['pdmx2'], '클레멘티 소나티네 Op.36-1 주제', 'Sonatina Op.36 No.1 — 1악장 주제', '무치오 클레멘티 (Muzio Clementi, 1752–1832)', 12, {}),
 ('bourree', r'^Bourrée in E Minor BWV996', 'Bach', ['Guitar'], ['pdmx2'], '부레 E단조', 'Bourrée in E minor BWV 996', '요한 제바스티안 바흐 (Johann Sebastian Bach, 1685–1750)', 16, {}),
 ('traumerei', r'^Tr[aä]umerei', 'Schumann', ['Piano'], ['mutopia','pdmx2'], '트로이메라이', 'Träumerei — 어린이 정경 Op.15 No.7', '로베르트 슈만 (Robert Schumann, 1810–1856)', 16, {}),
 ('carmen_habanera', r'^Carmen$', 'Bizet', ['Flute','Violin'], ['pdmx'], '카르멘 하바네라', 'Habanera — 카르멘', '조르주 비제 (Georges Bizet, 1838–1875)', 16, {}),
 ('santa_lucia', r'^Czerny - Air napolitain Santa Luci', 'Czerny', ['Piano'], ['pdmx2'], '산타 루치아', 'Santa Lucia — 나폴리 노래', '테오도로 코트라우 (Teodoro Cottrau, 1827–1879)', 16, {}),
 ('chopin_prelude7', r'^Chop 28 7$|Prelude.*Op\.? ?28.*No\.? ?7', 'Chopin', ['Piano'], ['mutopia','pdmx2'], '쇼팽 전주곡 7번', 'Prélude Op.28 No.7', '프레데리크 쇼팽 (Frédéric Chopin, 1810–1849)', 16, {}),
 ('nutcracker', r'^The Nutcracker \(ballet\)', 'Tchaik', ['Flute','Piano'], ['pdmx','pdmx2'], '호두까기 인형 주제', 'The Nutcracker Op.71 — 주제', '표트르 차이콥스키 (Pyotr Ilyich Tchaikovsky, 1840–1893)', 16, {}),
 ('schumann_melodie', r'schumann-op68-01|^Melodie', 'Schumann', ['Piano'], ['mutopia'], '멜로디 (유겐트 앨범 1번)', 'Melodie — 유겐트 앨범 Op.68 No.1', '로베르트 슈만 (Robert Schumann, 1810–1856)', 16, {}),
 ('soldatenmarsch', r'^Soldatenmarsch|Marche militaire.*Op\.? ?68|schumann-op68-02', 'Schumann', ['Piano'], ['mutopia'], '군인 행진곡 (유겐트 앨범 2번)', 'Soldatenmarsch — 유겐트 앨범 Op.68 No.2', '로베르트 슈만 (Robert Schumann, 1810–1856)', 16, {}),
 ('wilder_reiter', r'Cavalier sauvage|Wilder Reiter|schumann-op68-08', 'Schumann', ['Piano'], ['mutopia'], '용감한 기사 (유겐트 앨범 8번)', 'Wilder Reiter — 유겐트 앨범 Op.68 No.8', '로베르트 슈만 (Robert Schumann, 1810–1856)', 16, {}),
 ('heidenroslein', r'^Heidenröslein', 'Schubert', ['Voice+Piano'], ['openscore_lieder'], '들장미', 'Heidenröslein D.257', '프란츠 슈베르트 (Franz Schubert, 1797–1828)', 16, {}),
 ('an_die_musik', r'^An die Musik', 'Schubert', ['Voice+Piano'], ['openscore_lieder'], '음악에게', 'An die Musik D.547', '프란츠 슈베르트 (Franz Schubert, 1797–1828)', 16, {}),
 ('standchen', r'^Ständchen \(Schwanengesang', 'Schubert', ['Voice+Piano'], ['openscore_lieder'], '세레나데 (슈베르트)', 'Ständchen — 백조의 노래 D.957', '프란츠 슈베르트 (Franz Schubert, 1797–1828)', 16, {}),
 ('ave_maria', r'^Ellens Gesang III', 'Schubert', ['Voice+Piano'], ['openscore_lieder'], '아베 마리아 (슈베르트)', 'Ave Maria — Ellens Gesang III D.839', '프란츠 슈베르트 (Franz Schubert, 1797–1828)', 12, {}),
 ('lindenbaum', r'^Der Lindenbaum', 'Schubert', ['Voice+Piano'], ['openscore_lieder'], '보리수', 'Der Lindenbaum — 겨울 나그네 D.911', '프란츠 슈베르트 (Franz Schubert, 1797–1828)', 16, {}),
 ('nussbaum', r'^Der Nussbaum', 'Schumann', ['Voice+Piano'], ['openscore_lieder'], '호두나무', 'Der Nussbaum — 미르테의 꽃 Op.25', '로베르트 슈만 (Robert Schumann, 1810–1856)', 16, {}),
 ('widmung', r'^Widmung \(Myrthen', 'Schumann', ['Voice+Piano'], ['openscore_lieder'], '헌정', 'Widmung — 미르테의 꽃 Op.25', '로베르트 슈만 (Robert Schumann, 1810–1856)', 16, {}),
 ('mondnacht', r'^Mondnacht \(Liederkreis', 'Schumann', ['Voice+Piano'], ['openscore_lieder'], '달밤', 'Mondnacht — 리더크라이스 Op.39', '로베르트 슈만 (Robert Schumann, 1810–1856)', 16, {}),
 ('musensohn', r'^Der Musensohn', 'Schubert', ['Voice+Piano'], ['openscore_lieder'], '뮤즈의 아들', 'Der Musensohn D.764', '프란츠 슈베르트 (Franz Schubert, 1797–1828)', 16, {}),
 ('du_bist_die_ruh', r'^Du bist die Ruh \(Op\.59\)', 'Schubert', ['Voice+Piano'], ['openscore_lieder'], '그대는 나의 안식', 'Du bist die Ruh D.776', '프란츠 슈베르트 (Franz Schubert, 1797–1828)', 16, {}),
 ('je_te_veux', r'^Je te veux', 'Satie', ['Voice+Piano'], ['openscore_lieder'], '주 트 뵈 (당신을 원해요)', 'Je te veux — 왈츠 노래', '에릭 사티 (Erik Satie, 1866–1925)', 16, {}),
]
